### ISSUE TITLE
Portal Frame Config?

### ISSUE THREAD

**Issue by Dumpling00** [Kitteh6660/Ceilands#6]
Love the dimension. Only real issue I personally have with it is the activation via the Ancient City's portal - mostly because I have the Deeper and Darker mod installed. Although I quite like the idea of being able to travel to two different dimensions depending on what activator you use on the frame, I'd like to request a config option to set up a custom portal frame. Could this be possible?

Thank you in advance for your time and patience.

**Comment by Kitteh6660** [comment]
You can configure which blocks are accepted via data packs!

https://github.com/Kitteh6660/Ceilands/blob/main/common/src/main/resources/data/ceilands/tags/blocks/ceilands_portal_frame_blocks.json

**Comment by Dumpling00** [comment]
Oh fantastic, thank you!
I can't seem to make it work though, could I please have more help? A template folder could help!

**Comment by Dumpling00** [comment]
Yeah sorry, unfortunately I can't seem to make it work?
This is how my datapack is setup - what am I doing wrong?

![image](https://github.com/Kitteh6660/Ceilands/assets/44829013/c86c4933-8402-4796-9397-7f54531af5e3)

and in the specified json I have:
{
  "replace": true,
  "values": [
    "minecraft:end_stone_bricks"
  ]
}

**Comment by Dumpling00** [comment]
Nevermind I'm dumb! Forgot to close all of this in one folder.
Thank you!
