### ISSUE TITLE
Void kill config

### ISSUE THREAD

**Issue by Dumpling00** [Kitteh6660/Ceilands#7]
Hello! Great fan of the mod!
I've been trying to make it fit in my modpack, progression wise, and I was wondering if there's any way to make it so falling through the void kills the player rather than teleporting them back to the overworld.

That would be extremely appreciated.

Thank you so much for your time and patience.

**Comment by Kitteh6660** [comment]
It can be done! I can add that in mod version 0.6.1.

**Comment by Kitteh6660** [comment]
Implemented as of mod version 0.6.1 for both MC 1.19.2 and 1.20.1.

Use the following command:

```/gamerule ceilandsVoidTeleport false```

The gamerule defaults to true, but setting it to false makes it so the void can kill.
