### ISSUE TITLE
Can't craft the ceilands portal activator

### ISSUE THREAD

**Issue by sigmasoldi3r** [Kitteh6660/Ceilands#8]
Maybe I'm missing some step?

![imagen](https://github.com/user-attachments/assets/1e58e19e-8f41-4f29-af55-d3ffdc0a573f)

The mod is working tho:

![imagen](https://github.com/user-attachments/assets/19550501-3b42-4f50-995b-3387daccaf91)

**Comment by Kitteh6660** [comment]
You're missing a stick at the bottom middle slot.

The hint is in the recipe book which I've noticed is missing as I've designed the Ceilands to follow a very vanilla design.

**Comment by sigmasoldi3r** [comment]
cool! then the problem is with EMI

**Comment by Kitteh6660** [comment]
I realize that the portal activator item is crafted using `forge:rods/wooden` and Fabric uses `c:rods/wooden`.

Like, why did the mod loader systems have to use different tags? I will have to fix parity in 0.6.2 at a point!
